# Generated by Django 5.1.15 on 2026-08-13 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('LUBRICANT', 'Lubricant'), ('ENGINE_OIL', 'Engine Oil'), ('COOLANT', 'Coolant'), ('CAR_ACCESSORY', 'Car Accessory'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(default='Piece', max_length=20, verbose_name='Unit')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Stock')),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimum Stock Level')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='idx_inventory_item_sku'), models.Index(fields=['category'], name='idx_inventory_item_category'), models.Index(fields=['is_active'], name='idx_inventory_item_is_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='chk_inventory_item_stock_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('DAMAGED', 'Damaged')], default='STOCK_IN', max_length=20, verbose_name='Transaction Type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('previous_stock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Stock')),
                ('new_stock', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='New Stock')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem', verbose_name='Inventory Item')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'db_table': 'inventory_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item'], name='idx_inv_trans_item'), models.Index(fields=['transaction_type'], name='idx_inv_trans_type'), models.Index(fields=['created_at'], name='idx_inv_trans_created')],
            },
        ),
    ]
