# Generated by Django 5.1.15 on 2026-08-13 10:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fuel Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Fuel Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('unit', models.CharField(default='Liter', max_length=20, verbose_name='Unit of Measurement')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
                ('minimum_stock_level', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimum Stock Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'db_table': 'fuel_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_fuel_type_name'), models.Index(fields=['code'], name='idx_fuel_type_code'), models.Index(fields=['is_active'], name='idx_fuel_type_is_active')],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Previous Price')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Price')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason for Change')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='fuel.fueltype', verbose_name='Fuel Type')),
            ],
            options={
                'verbose_name': 'Fuel Price History',
                'verbose_name_plural': 'Fuel Price History',
                'db_table': 'fuel_price_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tank_number', models.CharField(max_length=20, unique=True, verbose_name='Tank Number')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacity')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Quantity')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimum Quantity')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tanks', to='fuel.fueltype', verbose_name='Fuel Type')),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
                'db_table': 'tanks',
                'ordering': ['tank_number'],
                'indexes': [models.Index(fields=['fuel_type'], name='idx_tank_fuel_type'), models.Index(fields=['status'], name='idx_tank_status'), models.Index(fields=['tank_number'], name='idx_tank_number')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0), ('current_quantity__lte', models.F('capacity'))), name='chk_tank_quantity_within_capacity')],
            },
        ),
    ]
