# Generated by Django 5.1.15 on 2026-08-13 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Purchase Number')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Unit')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Cost')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Invoice Number')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='fuel.fueltype', verbose_name='Fuel Type')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='inventory.inventoryitem', verbose_name='Inventory Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='suppliers.supplier', verbose_name='Supplier')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='fuel.tank', verbose_name='Tank')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier'], name='idx_purchase_supplier'), models.Index(fields=['fuel_type'], name='idx_purchase_fuel_type'), models.Index(fields=['tank'], name='idx_purchase_tank'), models.Index(fields=['purchase_date'], name='idx_purchase_date'), models.Index(fields=['payment_status'], name='idx_purchase_payment_status')],
            },
        ),
    ]
