# Generated by Django 5.1.15 on 2026-08-13 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('LOW_FUEL_STOCK', 'Low Fuel Stock'), ('LOW_INVENTORY', 'Low Inventory'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('FAILED_PAYMENT', 'Failed Payment'), ('METER_DIFFERENCE', 'Meter Difference'), ('CREDIT_LIMIT_WARNING', 'Credit Limit Warning'), ('SHIFT_CASH_DIFFERENCE', 'Shift Cash Difference'), ('GENERAL', 'General')], default='GENERAL', max_length=30, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('related_object_model', models.CharField(blank=True, max_length=100, verbose_name='Related Object Model')),
                ('related_object_id', models.CharField(blank=True, max_length=100, verbose_name='Related Object ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_notification_user'), models.Index(fields=['is_read'], name='idx_notification_is_read'), models.Index(fields=['notification_type'], name='idx_notification_type'), models.Index(fields=['created_at'], name='idx_notification_created_at')],
            },
        ),
    ]
