# Generated by Django 5.1.15 on 2026-08-13 11:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('SALARIES', 'Salaries'), ('MAINTENANCE', 'Maintenance'), ('RENT', 'Rent'), ('SECURITY', 'Security'), ('CLEANING', 'Cleaning'), ('EQUIPMENT', 'Equipment'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('description', models.TextField(verbose_name='Description')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('receipt_reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Receipt Reference')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='idx_expense_category'), models.Index(fields=['expense_date'], name='idx_expense_date'), models.Index(fields=['payment_method'], name='idx_expense_payment_method'), models.Index(fields=['created_by'], name='idx_expense_created_by')],
            },
        ),
    ]
