# Generated by Django 5.1.15 on 2026-08-13 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pump_number', models.CharField(max_length=20, unique=True, verbose_name='Pump Number')),
                ('name', models.CharField(max_length=200, verbose_name='Pump Name')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Last Maintenance Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pumps', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Employee')),
            ],
            options={
                'verbose_name': 'Pump',
                'verbose_name_plural': 'Pumps',
                'db_table': 'pumps',
                'ordering': ['pump_number'],
            },
        ),
        migrations.CreateModel(
            name='PumpFuelType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_fuel_types', to='fuel.fueltype')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_fuel_types', to='pumps.pump')),
            ],
            options={
                'verbose_name': 'Pump Fuel Type',
                'verbose_name_plural': 'Pump Fuel Types',
                'db_table': 'pump_fuel_types',
                'unique_together': {('pump', 'fuel_type')},
            },
        ),
        migrations.AddField(
            model_name='pump',
            name='fuel_types',
            field=models.ManyToManyField(blank=True, related_name='pumps', through='pumps.PumpFuelType', to='fuel.fueltype'),
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nozzle_number', models.CharField(max_length=20, unique=True, verbose_name='Nozzle Number')),
                ('opening_meter_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Meter Reading')),
                ('closing_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Closing Meter Reading')),
                ('current_meter_reading', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Meter Reading')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='fuel.fueltype', verbose_name='Fuel Type')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='pumps.pump', verbose_name='Pump')),
            ],
            options={
                'verbose_name': 'Nozzle',
                'verbose_name_plural': 'Nozzles',
                'db_table': 'nozzles',
                'ordering': ['nozzle_number'],
                'indexes': [models.Index(fields=['pump'], name='idx_nozzle_pump'), models.Index(fields=['fuel_type'], name='idx_nozzle_fuel_type'), models.Index(fields=['status'], name='idx_nozzle_status'), models.Index(fields=['nozzle_number'], name='idx_nozzle_nozzle_number')],
                'constraints': [models.CheckConstraint(condition=models.Q(('closing_meter_reading__isnull', True), ('closing_meter_reading__gte', models.F('opening_meter_reading')), _connector='OR'), name='chk_closing_gte_opening'), models.CheckConstraint(condition=models.Q(('current_meter_reading__gte', models.F('opening_meter_reading'))), name='chk_current_gte_opening')],
            },
        ),
        migrations.AddIndex(
            model_name='pump',
            index=models.Index(fields=['pump_number'], name='idx_pump_pump_number'),
        ),
        migrations.AddIndex(
            model_name='pump',
            index=models.Index(fields=['status'], name='idx_pump_status'),
        ),
        migrations.AddIndex(
            model_name='pump',
            index=models.Index(fields=['assigned_employee'], name='idx_pump_assigned_employee'),
        ),
    ]
