# Generated by Django 5.1.15 on 2026-08-13 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PRICE_CHANGE', 'Price Change'), ('STOCK_ADJUSTMENT', 'Stock Adjustment'), ('SALE_CREATE', 'Sale Create'), ('SALE_CANCEL', 'Sale Cancel'), ('REFUND', 'Refund'), ('PURCHASE_CREATE', 'Purchase Create'), ('EXPENSE_CREATE', 'Expense Create'), ('PERMISSION_CHANGE', 'Permission Change'), ('OTHER', 'Other')], db_index=True, max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model Name')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Object ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('previous_value', models.JSONField(blank=True, null=True, verbose_name='Previous Value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='New Value')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_audit_log_user'), models.Index(fields=['action'], name='idx_audit_log_action'), models.Index(fields=['model_name'], name='idx_audit_log_model_name'), models.Index(fields=['created_at'], name='idx_audit_log_created_at')],
            },
        ),
    ]
