# Generated by Django 5.1.15 on 2026-08-13 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pumps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Opening Cash')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Closing Cash')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Cash')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Actual Cash')),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cash Difference')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Sales')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total Transactions')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pumps.pump', verbose_name='Pump')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Opening Reading')),
                ('closing_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Closing Reading')),
                ('fuel_dispensed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fuel Dispensed')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Sales Count')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='pumps.nozzle', verbose_name='Nozzle')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='shifts.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'db_table': 'meter_readings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee'], name='idx_shift_employee'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['pump'], name='idx_shift_pump'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status'], name='idx_shift_status'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['start_time'], name='idx_shift_start_time'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['shift'], name='idx_meter_reading_shift'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['nozzle'], name='idx_meter_reading_nozzle'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['date'], name='idx_meter_reading_date'),
        ),
    ]
