# Generated by Django 5.1.15 on 2026-08-13 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=300, verbose_name='Company Name')),
                ('contact_person', models.CharField(blank=True, default='', max_length=200, verbose_name='Contact Person')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('tax_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Tax Number')),
                ('bank_details', models.TextField(blank=True, default='', verbose_name='Bank Details')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='idx_supplier_company_name'), models.Index(fields=['phone'], name='idx_supplier_phone'), models.Index(fields=['status'], name='idx_supplier_status')],
            },
        ),
    ]
