# Generated by Django 5.1.15 on 2026-08-13 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('is_corporate', models.BooleanField(default=False, verbose_name='Is Corporate')),
                ('company_name', models.CharField(blank=True, max_length=300, verbose_name='Company Name')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax Number')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Limit')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding Balance')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('VAN', 'Van'), ('OTHER', 'Other')], default='CAR', max_length=20, verbose_name='Vehicle Type')),
                ('make', models.CharField(blank=True, max_length=100, verbose_name='Make')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer', verbose_name='Customer')),
                ('preferred_fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_vehicles', to='fuel.fueltype', verbose_name='Preferred Fuel Type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='idx_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='idx_customer_email'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_corporate'], name='idx_customer_is_corporate'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status'], name='idx_customer_status'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['customer'], name='idx_vehicle_customer'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='idx_vehicle_reg_num'),
        ),
    ]
