# Generated by Django 5.1.15 on 2026-08-13 11:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('fuel', '0001_initial'),
        ('pumps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Receipt Number')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Unit')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='Tax Rate')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('DIGITAL_WALLET', 'Digital Wallet'), ('CREDIT', 'Credit'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='fuel.fueltype', verbose_name='Fuel Type')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pumps.nozzle', verbose_name='Nozzle')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pumps.pump', verbose_name='Pump')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(max_length=50, unique=True, verbose_name='Refund Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Refund Amount')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['receipt_number'], name='idx_sale_receipt_number'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer'], name='idx_sale_customer'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['employee'], name='idx_sale_employee'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['pump'], name='idx_sale_pump'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['fuel_type'], name='idx_sale_fuel_type'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method'], name='idx_sale_payment_method'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='idx_sale_status'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='idx_sale_created_at'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['sale'], name='idx_refund_sale'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['processed_by'], name='idx_refund_processed_by'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='idx_refund_status'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_refund_amount_positive'),
        ),
    ]
